/** Richtprijzen excl. btw. Geen officiële groothandelsprijslijst. */
export const LEVERANCIERS = [
  {
    id: "tu",
    naam: "Technische Unie",
    tak: "Elektra & installatie",
    artikelen: [
      ["WCD inbouw polarwit", "st", 2.45],
      ["WCD spatwaterdicht IP44", "st", 9.8],
      ["Schakelaar wissel polarwit", "st", 3.1],
      ["Inbouwdoos 50mm", "st", 0.85],
      ["Lasdoos opbouw", "st", 1.9],
      ["YMvK 3×2,5 mm²", "m", 1.85],
      ["YMvK 5×2,5 mm²", "m", 2.95],
      ["VD-draad 2,5 mm² blauw", "m", 0.42],
      ["Aardlekautomaat 1P+N 16A", "st", 48],
      ["Hoofdschakelaar 40A 4P", "st", 39],
      ["Groepenkast 3-fase 12 groepen", "st", 289],
      ["LED-spot 5W inbouw", "st", 6.5],
      ["Kabelgoot 40×40 PVC", "m", 3.4],
      ["Kabelklem 16-20", "st", 0.18],
    ],
  },
  {
    id: "solar",
    naam: "Solar Nederland",
    tak: "Elektra",
    artikelen: [
      ["Installatieautomaat B16 1P", "st", 7.9],
      ["Aardlekschakelaar 40A 30mA", "st", 42],
      ["KNX schakelaar 4-voud", "st", 86],
      ["Datakabel Cat6 UTP", "m", 0.55],
      ["RJ45 connector Cat6", "st", 0.35],
      ["Verdeelinrichting 24 modules", "st", 64],
      ["Din-rail 35mm 1m", "st", 3.2],
      ["Wago lasklem 3-voud", "st", 0.28],
      ["Kabelhaspel 25m 3×2,5", "st", 48],
      ["Multimeter vak", "st", 79],
    ],
  },
  {
    id: "rexel",
    naam: "Rexel",
    tak: "Elektra",
    artikelen: [
      ["Bewegingsmelder 180°", "st", 24],
      ["Schemerschakelaar", "st", 19],
      ["LED-armatuur 120cm 36W", "st", 22],
      ["Noodverlichting exit", "st", 38],
      ["Kabel YMvKas 4×6", "m", 6.4],
      ["Buis 16mm 3m", "st", 1.65],
      ["Bocht 16mm", "st", 0.45],
      ["Trekveer 10m", "st", 12],
      ["Tape isolatie PVC", "rol", 1.1],
    ],
  },
  {
    id: "wasco",
    naam: "Wasco",
    tak: "CV & sanitair",
    artikelen: [
      ["CV-ketel combitoestel 24kW", "st", 1450],
      ["Radiator 600×1000 type 22", "st", 89],
      ["Thermostatisches ventiel", "st", 18],
      ["Pex 16mm rol 50m", "rol", 42],
      ["Alupex 16×2 koppeling", "st", 3.8],
      ["Vloerverwarming verdeler 8 groepen", "st", 265],
      ["Expansievat 18L", "st", 38],
      ["Overstortventiel 3 bar", "st", 12],
      ["Rookgasafvoer 60/100 1m", "st", 28],
      ["Condensafvoer sifon", "st", 16],
    ],
  },
  {
    id: "warmte",
    naam: "Warmteservice",
    tak: "CV & warmtepomp",
    artikelen: [
      ["Warmtepomp lucht/water 8kW", "st", 4200],
      ["Buffervat 200L", "st", 490],
      ["Circulatiepomp A-label", "st", 145],
      ["Magneetfilter CV", "st", 68],
      ["Inhibitor 1L", "st", 18],
      ["Kamerthermostaat slim", "st", 129],
      ["Koper 15mm harde buis", "m", 8.9],
      ["Soldeerring 15mm", "st", 0.55],
    ],
  },
  {
    id: "pont",
    naam: "PontMeyer",
    tak: "Hout & plaat",
    artikelen: [
      ["Vuren regel 44×70 geschaafd", "m", 2.85],
      ["Vuren balk 75×175", "m", 9.4],
      ["OSB 18mm 244×122", "plaat", 18],
      ["Underlayment 18mm FSC", "plaat", 22],
      ["MDF 18mm 244×122", "plaat", 24],
      ["Betonplex 18mm", "plaat", 48],
      ["Gipsplaat 12,5mm 260×120", "plaat", 6.9],
      ["Metalstud C 50mm", "st", 4.2],
      ["Schroef gips 3,9×35 (200)", "doos", 6.5],
      ["Wiggen zak", "zak", 4.8],
    ],
  },
  {
    id: "stiho",
    naam: "Stiho",
    tak: "Hout",
    artikelen: [
      ["Rabat vuren 18×140", "m", 3.6],
      ["Vlonderplank hardhout 21×145", "m", 8.2],
      ["Paal 7×7 geïmpregneerd 2,7m", "st", 14],
      ["Lat 18×28", "m", 0.85],
      ["Pallet vuren 80×120", "st", 12],
      ["Kozijnhout meranti 67×114", "m", 18],
    ],
  },
  {
    id: "jongeneel",
    naam: "Jongeneel",
    tak: "Hout & plaat",
    artikelen: [
      ["Multiplex okoumé 18mm", "plaat", 62],
      ["Trespa 6mm antraciet", "plaat", 95],
      ["HPL werkblad 38mm", "m¹", 48],
      ["MDF vochtwerend 18mm", "plaat", 29],
      ["Fineer eiken 18mm", "plaat", 78],
    ],
  },
  {
    id: "rk",
    naam: "Raab Karcher",
    tak: "Bouwmaterialen",
    artikelen: [
      ["Snelbouwsteen 100mm", "st", 0.72],
      ["Kalkzandsteen 100mm", "st", 1.15],
      ["Lijmmortel zak 25kg", "zak", 8.9],
      ["Cement CEM I 25kg", "zak", 7.4],
      ["Zand metsel 25kg", "zak", 3.2],
      ["Isolatie PIR 80mm 600×1200", "plaat", 18],
      ["Steenwolplaat 70mm", "m²", 6.8],
      ["Dakpan keramisch", "st", 1.35],
      ["Panlat 22×38", "m", 0.95],
      ["Dampfolie 1,5×50m", "rol", 42],
    ],
  },
  {
    id: "bmn",
    naam: "BMN",
    tak: "Bouwmaterialen",
    artikelen: [
      ["Cellenbeton 600×200×100", "st", 2.4],
      ["Lijmblokken 7 N/mm²", "st", 2.1],
      ["Stucwerk gips 25kg", "zak", 11],
      ["Egaline 25kg", "zak", 14],
      ["Tegellijm poeder 25kg", "zak", 9.5],
      ["Voegmortel 5kg", "zak", 6.2],
      ["Kit sanitair wit", "koker", 4.8],
      ["PU-schuim bus", "st", 5.9],
    ],
  },
  {
    id: "bouwmaat",
    naam: "Bouwmaat",
    tak: "Vakhandel",
    artikelen: [
      ["Hamer 500g", "st", 12],
      ["Waterpas 60cm", "st", 9.5],
      ["Accuschroefmachine 18V", "st", 149],
      ["Bitset 32-delig", "set", 8],
      ["Afplaktape 50mm", "rol", 2.4],
      ["Folie afdek 4×5m", "st", 3.9],
      ["Emmer 12L", "st", 2.8],
      ["Werkhandschoen paar", "paar", 2.2],
    ],
  },
  {
    id: "hornbach",
    naam: "Hornbach",
    tak: "Bouwmarkt",
    artikelen: [
      ["Betonmixer huur dag", "dag", 38],
      ["Steigerdeel 2m", "st", 42],
      ["Ladder 3-delig", "st", 89],
      ["Kwastset 5-delig", "set", 7.5],
      ["Latex muurverf 10L wit", "blik", 32],
      ["Grondverf hout 2,5L", "blik", 28],
      ["Schuurpapier P120 (50)", "pak", 6],
    ],
  },
  {
    id: "gamma",
    naam: "GAMMA Pro",
    tak: "Bouwmarkt",
    artikelen: [
      ["Siliconenkit grijs", "koker", 5.2],
      ["Montagelijm koker", "koker", 4.6],
      ["Pluggen 8mm (50)", "doos", 3.8],
      ["Houtdraadbout 6×80 (20)", "doos", 4.1],
      ["Snelcement 5kg", "zak", 6.9],
      ["Kimband 10m", "rol", 8.4],
    ],
  },
  {
    id: "fabory",
    naam: "Fabory",
    tak: "Bevestiging",
    artikelen: [
      ["Bout M8×40 RVS (25)", "doos", 5.6],
      ["Moer M8 RVS (50)", "doos", 3.2],
      ["Sluitring M8 (50)", "doos", 1.8],
      ["Draadeind M10 1m", "st", 2.4],
      ["Chemisch anker koker", "st", 14],
      ["Keilbout M10", "st", 1.15],
      ["Tacker nieten (5000)", "doos", 9.5],
    ],
  },
  {
    id: "dak",
    naam: "BMI / Icopal",
    tak: "Dak",
    artikelen: [
      ["Bitumenbaan APP 4mm", "rol", 89],
      ["Daktrim aluminium 2,5m", "st", 18],
      ["Hemelwaterafvoer 80mm", "m", 6.4],
      ["Bladvanger", "st", 8.9],
      ["Dakdoorvoer 110mm", "st", 24],
      ["EPDM lijm 5L", "blik", 48],
    ],
  },
];

export function alleArtikelen() {
  return LEVERANCIERS.flatMap((l) =>
    l.artikelen.map(([naam, eenheid, prijs], i) => ({
      id: l.id + "-" + i,
      leverancier: l.naam,
      tak: l.tak,
      naam,
      eenheid,
      prijs,
    }))
  );
}
